# fly.toml app configuration file generated for muuuxy on 2025-05-30T22:40:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'muuuxy'
primary_region = 'gru'

[build]

[env]
MUUUXY_SERVER_SCHEME = 'https'
MUUUXY_SERVER_HOST = '0.0.0.0'
MUUUXY_SERVER_PORT = '8080'
MUUUXY_SERVER_DOMAIN = 'muuuxy.fly.dev'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
