# fly.toml app configuration file generated for muuuxy on 2025-06-05T03:39:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'muuuxy'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
