name: muuuxy
services:
  muuuxy:
    build:
      context: ../
      dockerfile: Containerfile
    ports:
      - 3000:80
    environment:
      MUUUXY_SERVER_HOST: "0.0.0.0"
      MUUUXY_SERVER_PORT: "80"
      MUUUXY_SERVER_SCHEME: "http"
      MUUUXY_SERVER_DOMAIN: "localhost"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:80/healthz"]
      start_period: 5s
      interval: 5s
      timeout: 30s
      retries: 3
